const app = document.querySelector('#app');
const invoke = window.__TAURI__.core.invoke;
let page = 'home';
let message = '';

const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const wyn = value => `${String(value ?? '0.00000000').replace('.', ',')} WYN`;
const call = async (command, args = {}) => invoke(command, args);
const notice = () => message ? `<p class="notice ${message.type === 'error' ? 'error' : ''}">${esc(message.text)}</p>` : '';
function shell(content) { return `<header><div class="brand"><span class="mark">W</span><div><h1>WynCoin Wallet</h1><small>Carteira local para a testnet</small></div></div><button class="secondary" data-action="lock">Bloquear</button></header>${notice()}${content}`; }
function tabs() { return `<nav class="tabs"><button class="${page==='home'?'active':''}" data-page="home">Visão geral</button><button class="${page==='receive'?'active':''}" data-page="receive">Receber</button><button class="${page==='send'?'active':''}" data-page="send">Enviar</button><button class="${page==='history'?'active':''}" data-page="history">Histórico</button><button class="${page==='settings'?'active':''}" data-page="settings">Nó</button></nav>`; }

async function onboarding(state) { app.innerHTML = shell(`<section class="grid"><article class="panel"><h2>${state.exists ? 'Desbloquear carteira' : 'Criar carteira protegida'}</h2><form id="wallet-form" class="stack">${state.exists ? '<label>Senha<input name="password" type="password" autocomplete="current-password" required /></label>' : '<label>Senha (mínimo 8 caracteres)<input name="password" type="password" autocomplete="new-password" minlength="8" required /></label><label>Confirmar senha<input name="confirm" type="password" autocomplete="new-password" minlength="8" required /></label>'}<button>${state.exists ? 'Desbloquear' : 'Criar carteira'}</button></form></article><aside class="panel"><h2>Segurança</h2><p class="muted">A chave privada é criptografada localmente. A senha não sai deste aplicativo e não pode ser recuperada.</p>${state.exists ? '' : `<h3>Importar carteira antiga</h3><form id="import-form" class="stack"><label>Arquivo JSON legado<input name="legacyPath" placeholder="/home/voce/.wyncoin/wallet.json" required /></label><label>Nova senha (mínimo 8 caracteres)<input name="password" type="password" minlength="8" required /></label><p class="notice">A importação não apaga o JSON antigo. Depois de confirmar que a nova carteira abre, mova o arquivo legado para um backup protegido.</p><button class="secondary">Importar e proteger</button></form>`}</aside></section>`); }

async function dashboard() { const overview = await call('wallet_overview'); app.innerHTML = shell(`${tabs()}<section class="grid"><article class="panel"><small>SALDO DISPONÍVEL</small><div class="balance">${wyn(overview.available_wyn)}</div><p class="muted">${overview.utxo_count} UTXO(s) utilizável(is). Coinbases recentes podem continuar bloqueadas por maturidade.</p><p class="address">${esc(overview.address)}</p><div class="actions"><button data-page="receive">Receber</button><button class="secondary" data-copy="${esc(overview.address)}">Copiar endereço</button></div></article><aside class="panel"><h2>Nó local</h2><p><strong>${esc(overview.node.network_id)}</strong></p><p class="muted">Altura ${esc(overview.node.height)} · mempool ${esc(overview.node.mempool_size)}</p><p class="muted">Mineração local: ${overview.node.mining_enabled ? 'ativa' : 'pausada'}</p></aside></section>`); }

async function receive() { const [overview, svg] = await Promise.all([call('wallet_overview'), call('receive_qr_svg')]); app.innerHTML = shell(`${tabs()}<section class="grid"><article class="panel"><h2>Receber WYN</h2><p class="address">${esc(overview.address)}</p><div class="actions"><button data-copy="${esc(overview.address)}">Copiar endereço</button></div><p class="muted">Compartilhe apenas o endereço público. Nunca compartilhe arquivo de carteira ou senha.</p></article><aside class="panel"><div class="qr">${svg}</div></aside></section>`); }

async function send() { const overview = await call('wallet_overview'); app.innerHTML = shell(`${tabs()}<section class="grid"><article class="panel"><h2>Enviar WYN</h2><p class="muted">Disponível: ${wyn(overview.available_wyn)}</p><form id="send-form" class="stack"><label>Destinatário<input name="to" placeholder="WYN..." required /></label><label>Valor a receber<input name="amount" inputmode="decimal" placeholder="50" required /></label><label>Taxa paga separadamente<input name="fee" inputmode="decimal" value="0.001" required /></label><p class="notice">O destinatário recebe o valor integral. Seu saldo precisa cobrir valor + taxa.</p><button>Assinar e enviar</button></form></article><aside class="panel"><h2>Revisão</h2><p class="muted">A transação será assinada localmente e enviada ao seu wyncoind em 127.0.0.1.</p></aside></section>`); }

async function history() { const items = await call('wallet_history'); const rows = items.length ? items.map(item => `<div class="row"><div><strong>${item.block_height === null ? 'Pendente' : `Bloco #${item.block_height}`}</strong><br><small>${esc(item.transaction_id)}</small></div><div class="amount ${item.is_receive ? 'in':'out'}">${item.is_receive ? '+':'-'}${wyn(item.amount_wyn)}<br><small>${item.confirmations} conf. · taxa ${wyn(item.fee_wyn)}</small></div></div>`).join('') : '<p class="muted">Nenhuma atividade encontrada.</p>'; app.innerHTML = shell(`${tabs()}<section class="panel"><h2>Histórico</h2><div class="history">${rows}</div></section>`); }

async function settings() { const address = await call('node_address'); app.innerHTML = shell(`${tabs()}<section class="grid"><article class="panel"><h2>Conexão local</h2><form id="node-form" class="stack"><label>Endereço do nó<input name="address" value="${esc(address)}" required /></label><p class="muted">A primeira versão aceita somente loopback. Não exponha a API do nó à internet.</p><button>Salvar conexão</button></form></article><aside class="panel"><h2>Carteira</h2><p class="muted">Arquivo protegido em ~/.wyncoin/wallets/default.wynwallet.</p><button class="danger" data-action="lock">Bloquear agora</button></aside></section>`); }

async function render() { try { const state = await call('wallet_state'); if (!state.unlocked) return onboarding(state); if (page==='receive') return receive(); if (page==='send') return send(); if (page==='history') return history(); if (page==='settings') return settings(); return dashboard(); } catch (error) { message = { type:'error', text: String(error) }; app.innerHTML = shell('<section class="panel"><h2>Não foi possível carregar a carteira.</h2><p class="muted">Confira se o wyncoind local está em execução.</p></section>'); console.error('[wyncoin-wallet]', error); } }

function showFormError(form, error) { const current = form.querySelector('.form-error'); if (current) current.remove(); const notice = document.createElement('p'); notice.className = 'notice error form-error'; notice.textContent = String(error); form.append(notice); }

document.addEventListener('click', async event => { const pageButton = event.target.closest('[data-page]'); if (pageButton) { message=''; page = pageButton.dataset.page; return render(); } const copy = event.target.closest('[data-copy]'); if (copy) { await navigator.clipboard.writeText(copy.dataset.copy); message = { text:'Endereço copiado.' }; return render(); } if (event.target.closest('[data-action="lock"]')) { await call('lock_wallet'); message=''; page='home'; return render(); } });
document.addEventListener('submit', async event => { event.preventDefault(); const form = event.target; const data = new FormData(form); try { if (form.id==='wallet-form') { const password = data.get('password'); if (data.get('confirm') !== null && password !== data.get('confirm')) throw new Error('As senhas não coincidem.'); const unlocking = form.querySelector('button').textContent.includes('Desbloquear'); await call(unlocking ? 'unlock_wallet' : 'create_wallet', { password }); message={text: unlocking ? 'Carteira desbloqueada.' : 'Carteira criada e protegida.'}; } else if (form.id==='import-form') { await call('import_legacy_wallet', { legacyPath:data.get('legacyPath'), password:data.get('password') }); message={text:'Carteira importada e protegida.'}; } else if (form.id==='send-form') { const result = await call('send_transaction', { to:data.get('to'), amount:data.get('amount'), fee:data.get('fee') }); message={text:`Transação enviada: ${result.txid}`}; page='history'; } else if (form.id==='node-form') { await call('set_node_address', { address:data.get('address') }); message={text:'Nó local atualizado.'}; page='home'; } await render(); } catch (error) { showFormError(form, error); console.error('[wyncoin-wallet]',error); } });
render();
